### ISSUE TITLE
LoupeLogger logs incorrect levels

### ISSUE THREAD

**Issue by DavidJFowler** [GibraltarSoftware/Loupe.Agent.Core#11]
Loupe.Extensions.Logging.LoupeLogger appears to be recording incorrect log levels.

Loupe.Extensions.Logging v4.5.0.1 dot net core 1.1 Windows 8.

In the following code the Log... method calls record correct levels, but the LoupeLogger calls do not:

`

        static void Main(string[] args)
        {
            var services = new ServiceCollection();

            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

            var configuration = builder.Build();
            services.AddOptions();

            var loggerFactory = new LoggerFactory()
                .AddConsole(configuration.GetSection("Logging"))
                .AddDebug().AddLoupe();
            services.AddSingleton(loggerFactory);
            services.AddLogging();

            services.Configure<AgentConfiguration>(configuration.GetSection("Loupe"));

            var provider = services.BuildServiceProvider();

            var agentConfiguration = provider.GetService<IOptions<AgentConfiguration>>().Value;
            Log.StartSession(agentConfiguration);

            Log.Information("InterceptorTest.HelloWorld", "Info", "The info description");
            Log.TraceInformation("Trace", "The trace description");
            Log.Warning("InterceptorTest.HelloWorld", "Warning", "The warn description");
            Log.Error("InterceptorTest.HelloWorld", "Error", "The error description");
            Log.Critical("InterceptorTest.HelloWorld", "Critical", "The critical description");

            var logger = loggerFactory.CreateLogger("InterceptorTest.HelloWorld");
            logger.LogInformation("Info");
            logger.LogTrace("Trace");
            logger.LogWarning("Warning");
            logger.LogError("Error");
            logger.LogCritical("Critical");

            Log.EndSession();
        }

`

Screen shot from Loupe desktop client attached:

![image](https://user-images.githubusercontent.com/10775668/30375976-7a8e8518-9882-11e7-961c-b94e0abb2be3.png)

**Comment by kendallmiller** [comment]
Thanks for that report - we found and fixed a similar issue in another part (related to a change in .NET Core enumeration values vs. .NET Framework) and will hunt this one down.

**Comment by kendallmiller** [comment]
Wait, can you confirm that you're using the latest NuGet package for Loupe.Extensions.Logging?  This is exactly the place we found and fixed this problem.

**Comment by DavidJFowler** [comment]
> Wait, can you confirm that you're using the latest NuGet package for Loupe.Extensions.Logging? This is exactly the place we found and fixed this problem.

![image](https://user-images.githubusercontent.com/10775668/30377102-837a590a-9886-11e7-9b4d-6368b208ac65.png)

**Comment by kendallmiller** [comment]
Indeed.  Publishing [4.5.0.2](https://www.nuget.org/packages/Loupe.Extensions.Logging/4.5.0.2) now with fix.  Sorry for missing that in our last update publish.
