### ISSUE TITLE
AgentConfiguration constructor should initialise the Properties property

### ISSUE THREAD

**Issue by DavidJFowler** [GibraltarSoftware/Loupe.Agent.Core#12]
As it is not possible to set AgentConfiguration.Properties to an empty dictionary in a json appsettings file it is necessary to initialise the Properties property of AgentConfiguration in code, otherwise an exception is thrown in the Gibraltar.Monitor.SessionSummary constructor on calling Log.StartSession(configuration).

It would be convenient if the AgentConfiguration parameterless constructor initialised the Properties property to an empty dictionary or, alternatively, prevent exceptions when Properties is null.

**Comment by kendallmiller** [comment]
Good point, and we'd want it to work that way as well.  We'll investigate and make the change.

**Comment by kendallmiller** [comment]
Resolved in pull request #13.
