### ISSUE TITLE
Assembly load error on Microsoft.Extensions.Logging.Abstractions with .Net Standard Class Library and Azure Function app

### ISSUE THREAD

**Issue by DavidJFowler** [GibraltarSoftware/Loupe.Agent.Core#14]
In my solution I have the following:

A .Net Framework 4.6.1 Azure Function app project and a .Net Standard 2.0 class library.

My class library references Loupe.Extensions.Logging v4.5.0.3 and Microsoft.Extensions.Logging.Abstractions 2.0.0

I have a method in the class library that instantiates a LoupeLoggerProvider

If I call the class library method from my azure function the following exception is thrown:

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

See the attached solution:
[FunctionApp1.zip](https://github.com/GibraltarSoftware/Loupe.Agent.Core/files/1421806/FunctionApp1.zip)

To reproduce, debug the azure function locally, and call the function from a web browser:

http://localhost:7071/api/Function1?name=hello

**Comment by DavidJFowler** [comment]
I think this is an issue with the azure sdk:

https://github.com/Azure/azure-webjobs-sdk-script/issues/1792

**Comment by kendallmiller** [comment]
Thanks for your diligence in investigating and closing; it really saves us time!
