### ISSUE TITLE
OS Version Information Missing

### ISSUE THREAD

**Issue by kendallmiller** [GibraltarSoftware/Loupe.Agent.Core#2]
We traditionally P/Invoked to get the OS Version Info so we could tell people exactly what the OS was. Microsoft has made that unreliable as of Windows 8.1 by having OS Version Info lie, for reasons no one seems to fathom. Regardless, doing a P/Invoke seems like a questionable idea now anyway but we still want some way to capture and display OS information within the limitations of what Loupe captures today (we may change that for 5.0).

The OS information is captured as part of the constructor for Gibraltar.Monitor.SessionSummary in the Core project.  Since Loupe traditionally captured the output of [GetVersionEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx) we only stored a few data points, not the string values of what we found.  We'll have to change this for Loupe 5 when we can break compatibility but meanwhile we should do the best with what we have which are:

* **OSPlatformCode**: An integer to indicate platform.  Currently aligns with an MS enumeration which we can probably keep for now
* **OSVersion**: This needs to get populated with the best OS version we can find, presently it's not populated.
* **OSServicePack**: This is a string field, historically populated with things like "Service Pack 1".  It may not be relevant for Linux or Mac.

We need to be sure whatever we do will work with Windows, Linux, and MacOs.

**Comment by vcsjones** [comment]
A few thoughts on how to solve this.

1. `OSPlatformCode` - This can more or less be obtained with `System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform`. You will be able to at least determine between Linux, macOS, and Windows.

1. OSVersion - this is a little more difficult. There is no way in .NET Core, out-of-the-box, to do this. You will likely have to fall back to p/invoke - again, and do different p/invoke in for each platform. You may be able to re-use the Windows P/Invoke you had before, and macOS and Linux can P/Invoke the `uname` posix function. [Here's an example for macOS][1]. This is going to be kind of a whack-a-mole game, and ultimately you may not be able to figure it out. This gist is similar to [what Chrome does][2].

1. OSServicePack - it's relevant to Mac, kind of, I'm trying to dig out the right way to do this.

So I'm not sure how jazzed you are about basically doing the same solution but with different p/invoke per platform.


[1]: https://gist.github.com/vcsjones/a9289df560050092666773913f14abb0
[2]: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/mac/VersionUtilMac.mm

**Comment by kendallmiller** [comment]
My initial thought was that we had to get rid of the P/Invoke entirely but as I think about it a bit more, as long as we have confidence we're on the right platform..  it's OK.  My big fear with that is always "could we crash the process?" and it does crack that door slightly.

**Comment by kendallmiller** [comment]
This is fixed in .NET Standard 2 with Pull Request #29
