### ISSUE TITLE
assemblies are not signed.

### ISSUE THREAD

**Issue by shahrokhshirzad** [GibraltarSoftware/Loupe.Agent.Core#55]
Could you sign all of you assemblies, please?

I'm stuck with unsigned "Loupe.Core.NETCore" error when I tried using Loupe.Extentensions.Logging nuget for my firm (one of your clients) .

Kind Regards,

**Comment by kendallmiller** [comment]
We can; I had honestly thought we'd left all of that behind with .NET Core but clearly no!  We'll investigate and get that done.

**Comment by shahrokhshirzad** [comment]
Thanks!

**Comment by kendallmiller** [comment]
Fixed in 4.8.2.0
