### ISSUE TITLE
NETStandard

### ISSUE THREAD

**Issue by markrendle** [GibraltarSoftware/Loupe.Agent.Core#6]
Just want to raise this for discussion.

Currently Loupe.Core.NETCore targets `netcoreapp1.1`, which means it can only be used on .NET Core.

It can't be switched to `netstandard1.6`, which `netcoreapp1.1` supports, because the Standard doesn't include threading primitives like WaitCallback or the ThreadPool.

The newer `netstandard2.0` includes everything and the projects build fine, and those assemblies could be used in Core, .NET, Mono and Xamarin (and UWP after the Windows 10 <s>Fall</s> **Autumn** Creators' Update).

It would be reasonably straightforward to create an additional project targeting the same source directory, so we could build a NETCore package for `netcoreapp1.1` and a plain `Loupe.Core` package for `netstandard2.0`. The only possible issue is the potential confusion for customers from having multiple packages.

**Comment by kendallmiller** [comment]
For the moment we want to encourage .NET Full framework to use the real full agent (Gibraltar.Agent) as it has more functionality than this one does.  But, having an option for Core, Xamarin, and UWP is a good thing.  I'm wondering can we make a single set of NuGet packages that have inside them .NET Core 1.1 and .NET Standard 2.0?

**Comment by markrendle** [comment]
Yes, that occurred to me after I wrote the issue. I'm looking into it.

**Comment by markrendle** [comment]
OK, opened #7 to add multi-targeting. Still supports `netcoreapp1.1`.
